# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: default

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    arguments: '--configuration releases'
    projects: '/home/tal/Desktop/myagent/_work/4/s/pipelines-dotnet-core.csproj'
  displayName: 'Build'


- script: dotnet pack -p Version=1.0.$(Build.BuildId) /home/tal/Desktop/myagent/_work/4/s/pipelines-dotnet-core.csproj
  displayName: 'Package' 

- script: dotnet nuget push --source "talso12345" --api-key az /home/tal/Desktop/myagent/_work/4/s/bin/Release/pipelines-dotnet-core.1.0.0.nupkg
  displayName: 'publish NuGet Package'